version: '3.8'

services:
  road-defect-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
      - WORKERS=1
      - MAX_FILE_SIZE=20971520  # 20MB
      - CLEANUP_AFTER_HOURS=24
      - DEVICE=cpu  # Use CPU for ECS (change to 'cuda' for GPU instances)
      - ROAD_MODEL_PATH=/app/models/road_segmentation.pth
      - DEFECT_MODEL_PATH=/app/models/defect_segmentation.pt
      - UPLOAD_DIR=/app/uploads
      - OUTPUT_DIR=/app/outputs
    volumes:
      - ./models:/app/models:ro  # Mount model files (read-only)
      - upload_data:/app/uploads
      - output_data:/app/outputs
      - ./logs:/app/logs
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '2.0'
        reservations:
          memory: 4G
          cpus: '1.0'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Redis for caching (if needed in future)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

  # Optional: Prometheus for monitoring
  # prometheus:
  #   image: prom/prometheus:latest
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #     - prometheus_data:/prometheus
  #   restart: unless-stopped

volumes:
  upload_data:
  output_data:
  # redis_data:
  # prometheus_data: